spring:
  datasource:
    url: jdbc:mysql://localhost:3306/recruit
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  servlet:
    multipart:
      max-file-size: 10MB  #单次上传文件最大不超过10MB
      max-request-size: 100MB  #文件总上传大小不超过100MB
server:
  port: 8080

swagger:
  enable: true